/**
 * Assemble a self-contained folder of the practice-mode pages for an HTTPS host.
 *
 *   npm run build:deploy
 *   npm run build:deploy -- --out <โฟลเดอร์ที่จะอัปขึ้น host>
 *
 * Same idea as the Sparring side's build_deploy.mjs: the dev pages load the
 * bundle from ../tfjs_build/ because the dev server serves this folder's root,
 * so the paths are rewritten and the bundle copied in beside the pages.
 *
 * No TF.js here -- exercise-scorer.js does its two matrix multiplies in plain JS.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const argv = process.argv.slice(2);
const argOf = (name, dflt) => {
  const i = argv.indexOf(name);
  return i >= 0 && argv[i + 1] ? argv[i + 1] : dflt;
};
const outDir = path.resolve(root, argOf('--out', 'deploy'));

const PAGES = ['exercise-play.html', 'exercise.html'];
// fixtures.json ไม่ต้องอัป มันใช้แค่ตอน npm test
const COPY = [
  ['web/pose-camera.js', 'pose-camera.js'],
  ['web/exercise-scorer.js', 'exercise-scorer.js'],
  ['tfjs_build/jab_siamese/bundle.json', 'tfjs_build/jab_siamese/bundle.json'],
  ['web/vendor/mediapipe/vision_bundle.mjs', 'vendor/mediapipe/vision_bundle.mjs'],
  ['web/vendor/mediapipe/vision_wasm_internal.js', 'vendor/mediapipe/vision_wasm_internal.js'],
  ['web/vendor/mediapipe/vision_wasm_internal.wasm', 'vendor/mediapipe/vision_wasm_internal.wasm'],
  ['web/vendor/mediapipe/vision_wasm_nosimd_internal.js',
   'vendor/mediapipe/vision_wasm_nosimd_internal.js'],
  ['web/vendor/mediapipe/vision_wasm_nosimd_internal.wasm',
   'vendor/mediapipe/vision_wasm_nosimd_internal.wasm'],
  ['web/models/pose_landmarker_full.task', 'models/pose_landmarker_full.task'],
];

const human = (n) => n < 1024 ? `${n} B`
  : n < 1024 ** 2 ? `${(n / 1024).toFixed(0)} KB`
  : `${(n / 1024 ** 2).toFixed(1)} MB`;

// Wipe only a folder this script created -- --out may point into another repo.
const STAMP = '.build-deploy-output';
if (fs.existsSync(outDir)) {
  const entries = fs.readdirSync(outDir);
  const ours = fs.existsSync(path.join(outDir, STAMP));
  if (entries.length > 0 && !ours && !argv.includes('--force')) {
    console.error(`refusing to wipe ${outDir}\n` +
      '  it is not empty and was not created by this script.\n' +
      '  pass --force if you really mean to replace its contents.');
    process.exit(2);
  }
  fs.rmSync(outDir, { recursive: true, force: true });
}
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, STAMP),
  'generated by scripts/build_deploy.mjs -- safe to delete, do not edit by hand\n');

let total = 0;
const missing = [];

for (const [from, to] of COPY) {
  const src = path.join(root, from);
  if (!fs.existsSync(src)) { missing.push(from); continue; }
  const dst = path.join(outDir, to);
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.copyFileSync(src, dst);
  const size = fs.statSync(dst).size;
  total += size;
  console.log(`  ${to.padEnd(48)} ${human(size)}`);
}

for (const page of PAGES) {
  const src = path.join(root, 'web', page);
  if (!fs.existsSync(src)) { missing.push(`web/${page}`); continue; }
  const html = fs.readFileSync(src, 'utf8').replaceAll("'../tfjs_build/", "'tfjs_build/");
  const dst = path.join(outDir, page);
  fs.writeFileSync(dst, html);
  const size = fs.statSync(dst).size;
  total += size;
  console.log(`  ${page.padEnd(48)} ${human(size)}  (paths rewritten)`);
}

if (missing.length) {
  console.error('\nFAIL: missing source files:');
  for (const m of missing) console.error('  ' + m);
  console.error('\nrun python scripts/export_web.py, and check web/models/ + web/vendor/');
  process.exit(1);
}

// Every local URL the pages name must exist in the bundle.
const refs = [];
for (const page of PAGES) {
  const html = fs.readFileSync(path.join(outDir, page), 'utf8');
  refs.push(...[...html.matchAll(/['"]((?:tfjs_build|models)\/[^'"]+)['"]/g)].map((m) => m[1]));
}
const broken = [...new Set(refs)].filter((r) => !fs.existsSync(path.join(outDir, r)));

console.log(`\n  total ${human(total)}   -> ${outDir}`);
console.log(`  page references ${new Set(refs).size} local file(s): ` +
  (broken.length ? `${broken.length} MISSING` : 'all present'));

if (broken.length) {
  console.error('\nFAIL: the page points at files not in the bundle:');
  for (const b of broken) console.error('  ' + b);
  process.exit(1);
}
