/**
 * Assemble a self-contained folder to upload to the HTTPS host.
 *
 *   npm run build:deploy
 *   npm run build:deploy -- --out <โฟลเดอร์ที่จะอัปขึ้น host>
 *
 * The dev layout cannot be uploaded as-is. web/index.html reaches UP out of its
 * own folder (`../tfjs_build/...`) because the dev server serves the repo root,
 * and a host serving only the web folder would 404 on the model. This rewrites
 * those paths and copies the model in beside the page, so the output folder
 * works wherever it is mounted.
 *
 * It also verifies that every local file the page references actually landed in
 * the bundle. A deploy that is missing the model does not fail loudly -- the
 * page just sits there, and on a phone there is no console to find out why.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const argv = process.argv.slice(2);
const argOf = (name, dflt) => {
  const i = argv.indexOf(name);
  return i >= 0 && argv[i + 1] ? argv[i + 1] : dflt;
};
const outDir = path.resolve(root, argOf('--out', 'deploy'));

// lite is deliberately excluded: 5.6 MB that the page never loads, and the
// training data was captured with the full model (see web/README.md).
const COPY = [
  ['web/pose-detector.js', 'pose-detector.js'],
  ['web/pose-features.js', 'pose-features.js'],
  // โหมดฝึกซ้อม (exercise.html) — ตัวให้คะแนนท่า jab เทียบท่าต้นแบบ
  // bundle.json มีทั้งน้ำหนักโมเดลและ embedding ของท่าต้นแบบอยู่ในไฟล์เดียว
  // fixtures.json ไม่ต้องอัป มันใช้แค่ตอน npm test
  ['web/pose-camera.js', 'pose-camera.js'],
  ['web/exercise-scorer.js', 'exercise-scorer.js'],
  ['tfjs_build/jab_siamese/bundle.json', 'tfjs_build/jab_siamese/bundle.json'],
  // MediaPipe + tfjs ที่โฮสต์เอง — กันกรณีเน็ตปลายทางบล็อก CDN
  ['web/vendor/tf.min.js', 'vendor/tf.min.js'],
  ['web/vendor/mediapipe/vision_bundle.mjs', 'vendor/mediapipe/vision_bundle.mjs'],
  ['web/vendor/mediapipe/vision_wasm_internal.js', 'vendor/mediapipe/vision_wasm_internal.js'],
  ['web/vendor/mediapipe/vision_wasm_internal.wasm', 'vendor/mediapipe/vision_wasm_internal.wasm'],
  ['web/vendor/mediapipe/vision_wasm_nosimd_internal.js',
   'vendor/mediapipe/vision_wasm_nosimd_internal.js'],
  ['web/vendor/mediapipe/vision_wasm_nosimd_internal.wasm',
   'vendor/mediapipe/vision_wasm_nosimd_internal.wasm'],
  ['web/models/pose_landmarker_full.task', 'models/pose_landmarker_full.task'],
  ['tfjs_build/pose_action/meta.json', 'tfjs_build/pose_action/meta.json'],
  ['tfjs_build/pose_action/model/model.json', 'tfjs_build/pose_action/model/model.json'],
  ['tfjs_build/pose_action/model/group1-shard1of1.bin',
   'tfjs_build/pose_action/model/group1-shard1of1.bin'],
];

const human = (n) => n < 1024 ? `${n} B`
  : n < 1024 ** 2 ? `${(n / 1024).toFixed(0)} KB`
  : `${(n / 1024 ** 2).toFixed(1)} MB`;

// The output folder is wiped before writing, so that a file removed from the
// bundle does not linger on the host. That is fine for the default `deploy/`,
// but --out often points into another repo's working tree -- refuse to delete
// anything we did not put there ourselves.
const STAMP = '.build-deploy-output';
if (fs.existsSync(outDir)) {
  const entries = fs.readdirSync(outDir);
  const ours = fs.existsSync(path.join(outDir, STAMP));
  if (entries.length > 0 && !ours && !argv.includes('--force')) {
    console.error(`refusing to wipe ${outDir}\n` +
      '  it is not empty and was not created by this script.\n' +
      '  pass --force if you really mean to replace its contents.');
    process.exit(2);
  }
  fs.rmSync(outDir, { recursive: true, force: true });
}
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, STAMP),
  'generated by scripts/build_deploy.mjs -- safe to delete, do not edit by hand\n');

let total = 0;
const missing = [];

for (const [from, to] of COPY) {
  const src = path.join(root, from);
  if (!fs.existsSync(src)) { missing.push(from); continue; }
  const dst = path.join(outDir, to);
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.copyFileSync(src, dst);
  const size = fs.statSync(dst).size;
  total += size;
  console.log(`  ${to.padEnd(48)} ${human(size)}`);
}

// The pages: same files, with the dev-only parent-directory hops removed.
//   index.html    the test harness (manual start, probability bars)
//   game.html     what the Unity WebView loads -- auto-starts, no UI
//   exercise.html      the jab practice mode, with the diagnostic panels
//   exercise-play.html the same mode stripped to camera/time/reps/accuracy/feedback
for (const page of ['index.html', 'game.html', 'exercise.html', 'exercise-play.html']) {
  const src = path.join(root, 'web', page);
  if (!fs.existsSync(src)) { missing.push(`web/${page}`); continue; }

  let html = fs.readFileSync(src, 'utf8');
  const before = html;
  html = html.replaceAll("'../tfjs_build/", "'tfjs_build/");
  if (html === before) {
    console.warn(`\n  note: no ../tfjs_build paths to rewrite in ${page} -- check that\n` +
      '        it still points at the model the dev-server way');
  }
  const dst = path.join(outDir, page);
  fs.writeFileSync(dst, html);
  const size = fs.statSync(dst).size;
  total += size;
  console.log(`  ${page.padEnd(48)} ${human(size)}  (paths rewritten)`);
}

if (missing.length) {
  console.error('\nFAIL: missing source files:');
  for (const m of missing) console.error('  ' + m);
  console.error('\nrun train_pose_model.py + convert_to_tfjs.py, and check web/models/');
  process.exit(1);
}

// Cross-check: every local URL the bundled pages name must exist in the bundle.
// Catches a renamed model folder or a stale path that the copy list did not cover.
const refs = [];
for (const page of ['index.html', 'game.html', 'exercise.html', 'exercise-play.html']) {
  const html = fs.readFileSync(path.join(outDir, page), 'utf8');
  refs.push(...[...html.matchAll(/['"]((?:tfjs_build|models)\/[^'"]+)['"]/g)].map((m) => m[1]));
}
const broken = [...new Set(refs)].filter((r) => !fs.existsSync(path.join(outDir, r)));

console.log(`\n  total ${human(total)}   -> ${outDir}`);
console.log(`  page references ${new Set(refs).size} local file(s): ` +
  (broken.length ? `${broken.length} MISSING` : 'all present'));

if (broken.length) {
  console.error('\nFAIL: the page points at files not in the bundle:');
  for (const b of broken) console.error('  ' + b);
  process.exit(1);
}

console.log(`
next:
  1. upload the contents of ${path.relative(root, outDir)}/ to the HTTPS host
  2. open <url>/ in desktop Chrome and punch -- the test harness. Confirms the
     host serves .task and .bin with the right types and the model loads at all
  3. point the Unity WebView at <url>/game.html -- NOT index.html. game.html
     starts the camera by itself; index.html waits for a button nobody can tap
     once the WebView is hidden
  4. first Android run: <url>/game.html?debug=1 with Visible = true, so the
     overlay shows whether the camera actually opened

the host must serve these over HTTPS (getUserMedia needs a secure context) and
must not gzip the .task file in a way that breaks range requests.`);
